site_name: ETL Project
site_description: ETL Project Documentation
site_author: Viacheslav Babanin
site_url: http://lh.pl/etlproject/
repo_url: https://github.com/Vjatches/etlproject/
copyright: © 2018 Uniwersytet Ekonomiczny w Krakowie
pages:
  - Home: index.md
  - Installation: installation.md
  - General Overview: overview.md
  - Tutorial: tutorial.md
  - Application Flow: flow.md
  - URI Routing : routing.md
  - Controllers : controller.md
  - Models : models.md
  - Views : views.md
  - Custom Libraries : libraries.md
  - Helper functions : helpers.md
  - Frontend Logic : frontend.md
  - Stylesheets : stylesheets.md
theme:
  name: 'rtd-dropdown'
extra_css:
  - css/uekrtd.css
markdown_extensions:
    - toc:
        permalink: 